version: '3.4'

services:
  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: psss11rwere
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5433:5432

  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379